name: Send Release Notes to Beamer

on:
  release:
    types: [published]

jobs:
  update-beamer:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send Release Notes to Beamer
      env:
        BEAMER_API_KEY: b_PUZ1AdU5J+6lxe/HIPEPblCIjQ7CKoF8PDJ+wBILNK4=
        BEAMER_TITLE: ${{github.event.release.tag_name}}
        BEAMER_CONTENT: ${{github.event.release.body}}
      run: |
        echo ${curl -X POST -H "Content-Type: application/json" -H "Beamer-Api-Key: $BEAMER_API_KEY" 
        -d '{
            "title": [
              "'"$BEAMER_TITLE"'"
            ],
            "content": [
              "'"$BEAMER_CONTENT"'"
            ],
            "category": "new",
            "publish": true
          }' 
        https://api.getbeamer.com/v0/posts
        }
